name: sendafrica_dart_sdk
description: A production-ready Dart client for the SendAfrica Tanzania SMS API.
version: 0.1.0
homepage: https://sendafrica.online
repository: https://github.com/fredy-me/SendAfrica-Dart-sdk
issue_tracker: https://github.com/fredy-me/SendAfrica-Dart-sdk/issues
topics:
  - sendafrica
  - sms
  - tanzania
  - africa
  - messaging

environment:
  sdk: ^3.10.4

dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
